[project]
name = "spring-boot-data-commons"
version = "4.2.0-SNAPSHOT"
group = "org.springframework.boot"
java_version = "21"

[build]
target_dir = "target/grine"
source_dir = "src/main/java"
resources_dir = "src/main/resources"

[build.compiler]
backend = "javac"

[dependencies]
"spring-boot" = "4.2.0-SNAPSHOT"
"spring-boot-autoconfigure" = "4.2.0-SNAPSHOT"
"spring-boot-persistence" = "4.2.0-SNAPSHOT"
"io.micrometer:micrometer-core" = "1.18.0-M1"
"org.springframework.data:spring-data-commons" = "4.1.0-M1"
"org.springframework:spring-webmvc" = "7.1.0-M1"
